// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABV0yxeX36uGfQpbS9sNpY9O0TKwgxB2o',
    appId: '1:825987077811:web:cb08aeb76e529665c402c6',
    messagingSenderId: '825987077811',
    projectId: 'inventot-49e3e',
    authDomain: 'inventot-49e3e.firebaseapp.com',
    storageBucket: 'inventot-49e3e.firebasestorage.app',
    measurementId: 'G-VJTFZ5M0S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHqBdP2t-s6kmxsgq1A3J88JFUjcVRE8M',
    appId: '1:825987077811:android:a56fde185428571dc402c6',
    messagingSenderId: '825987077811',
    projectId: 'inventot-49e3e',
    storageBucket: 'inventot-49e3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeA7MZxc-7sFuHTB05jmxGQCNyPheQHuc',
    appId: '1:825987077811:ios:51796b2814fef54bc402c6',
    messagingSenderId: '825987077811',
    projectId: 'inventot-49e3e',
    storageBucket: 'inventot-49e3e.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeA7MZxc-7sFuHTB05jmxGQCNyPheQHuc',
    appId: '1:825987077811:ios:51796b2814fef54bc402c6',
    messagingSenderId: '825987077811',
    projectId: 'inventot-49e3e',
    storageBucket: 'inventot-49e3e.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABV0yxeX36uGfQpbS9sNpY9O0TKwgxB2o',
    appId: '1:825987077811:web:cf89c1f5ae90067dc402c6',
    messagingSenderId: '825987077811',
    projectId: 'inventot-49e3e',
    authDomain: 'inventot-49e3e.firebaseapp.com',
    storageBucket: 'inventot-49e3e.firebasestorage.app',
    measurementId: 'G-MER606QTM8',
  );
}
